### ISSUE TITLE
Benutzung

### ISSUE THREAD

**Issue by immenz** [DerMitch/fritzbox-smarthome#1]
Hi, 

ist das tool schon nutzbar? wie bekomme ich es installiert? Über pip findet er entweder kein paket oder keine setup.py

**Comment by immenz** [comment]
Sorry wenn ich zu doof für die Installation bin, aber die setup.py scheint noch nicht dabei gewesen zu sein im letzten commit, obwohl in der Beschreibung angegeben...

**Comment by DerMitch** [comment]
Entschuldige bitte die Verwirrung. Die habe ich vorhin mit rein gepackt, aber kam noch nicht dazu alles zu testen. Ich melde mich, wenn das Setup sauber funktioniert und es auf PyPi ist.

**Comment by immenz** [comment]
Ok, Danke!

**Comment by kickbutts** [comment]
Hi. Geht es inzwische, oder bin ich zu blöd es zu installieren?

**Comment by DerMitch** [comment]
Entschuldigt bitte die lange Wartezeit...

Das Paket ist nun auf PyPi, inklusive von Bugfixes für die letzte Fritz!OS-Version.

Installation per pip:

```
pip install fritzhome==1.0.0b1
```

Sollte alles funktionieren nehme ich den Beta-Status weg, dann geht es auch ohne Versions-Angabe.
