### ISSUE TITLE
UniCode utf8 problem

### ISSUE THREAD

**Issue by hpd96** [DerMitch/fritzbox-smarthome#11]
Hallo,

if the smarthome device "Fritz Dect 200" is named "Stromzähler-1" there will be an error: 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 187: ordinal not in range(128)

clearance: rename "Stromzähler-1" to "Stroemzaehler"

Danke fürs tool, gruß hp

**Comment by DerMitch** [comment]
Ich kann das Problem mit Python 3.5.2 nicht reproduzieren. Falls dies wieder auftritt, wäre ein Stacktrace sehr hilfreich um herauszufinden wo das Problem genau auftritt.
