### ISSUE TITLE
Update of PyPi Package

### ISSUE THREAD

**Issue by BastianPoe** [DerMitch/fritzbox-smarthome#12]
The current package on PyPi unfortunately does not install on Raspbian GNU/Linux 8 (jessie) with Python 3:
```
$ pip3 install fritzhome
Collecting fritzhome
  Using cached fritzhome-1.0.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_w7yyo_n/fritzhome/setup.py", line 9, in <module>
        with open(path.join(here, "README.md"), encoding="utf-8") as f:
      File "/usr/lib/python3.4/codecs.py", line 896, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-_w7yyo_n/fritzhome/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_w7yyo_n/fritzhome/
```

The latest code on Github installs without a problem. Could you please update the package?

Background: I am working on a component for https://home-assistant.io based on your library. I want to automate the installation of the dependency and hence need the fixed package.

**Comment by DerMitch** [comment]
Version 1.0.2 based on the current git version has been released on PyPi.

[fritzhome 1.0.2 on pypi](https://pypi.python.org/pypi/fritzhome/1.0.2)

**Comment by BastianPoe** [comment]
Perfect, thank you vey much!
