### ISSUE TITLE
Exception if Actor Offline

### ISSUE THREAD

**Issue by CoReYeDe** [DerMitch/fritzbox-smarthome#18]
![2017-12-10 20_46_05-root lnx_ _fritzbox-smarthome](https://user-images.githubusercontent.com/22613068/33808713-4bec98ae-ddeb-11e7-8387-6335c53a0511.png)

I have 2 Actors. One of them is sometimes offline.
When the Actor is offline, the Script returns the Error in the Screenshot..

**Comment by DerMitch** [comment]
I pushed a possible fix into the master branch. Can't test it myself as I'm on vacation currently. Please test the fix and report back whether it works.

**Comment by CoReYeDe** [comment]
Wow.. awesome.. i have test it and now it works perfect..
Thank you for this great Script and your fast Support..

![2017-12-10 21_43_41-root lnx_ _fritzbox-smarthome_fritzbox-smarthome](https://user-images.githubusercontent.com/22613068/33809191-415a00a4-ddf3-11e7-98c5-09edf7c1f09b.png)
