### ISSUE TITLE
Adding temperature readout

### ISSUE THREAD

**Issue by jandechent** [DerMitch/fritzbox-smarthome#2]
Dear Mitch,
is it easy to add a readout for temperature? This would be aweseome to monitor in addition to the power consumption.

**Comment by DerMitch** [comment]
I added support in f0c32d618590910267ec3f74990b833b95d9b910
Please test it, then I'll make a new release for pypi.

`Actor.get_temperature` is not working yet, cause the method document by AVM throws 400 errors with my Fritz!BOX. But calling `get_actors` and accessing `actor.temperature` should hopefully work for most cases.
