### ISSUE TITLE
Actor not found

### ISSUE THREAD

**Issue by Mc-Raw** [DerMitch/fritzbox-smarthome#3]
Hallo

Irgendwie scheint bei den Schaltbefehlen was nicht richtig hinzuhauen. Wenn ich mir die Steckdosen anzeigen lasse werden diese zwar gefunden und auch der Energieverbrauch angezeigt,aber sobald ich die Steckdose schalten will bekomme ich immer "Actor not found: 087*********" ausgegeben. 

Actors
`(fritzenv) kodi@TV-Box:~$ fritzhome --password ****** actors`

`Steckdose Sat-Ip (AVM FRITZ!DECT 200; AIN 087** ********)`

`(fritzenv) kodi@TV-Box:~$`

Schalten
`(fritzenv) kodi@TV-Box:~$ fritzhome --password ******** switch-on 087*********`
`Actor not found: 087***********`
`(fritzenv) kodi@TV-Box:~$`

**Comment by DerMitch** [comment]
Hast Du bereits Firmware 06.50 (neue UI)? Damit ist die Library bisher noch nicht getestet, vielleicht hat AVM etwas an deren APIs umgebaut - die ist leider ziemlich schlecht dokumentiert :/

**Comment by Mc-Raw** [comment]
Ja ,hab gerade auf 06.51 geupdated weil das Kodi Plugin für die Steckdosen was ich nutze auf Version 06.01 Probleme gemacht hat und mir der Entwickler sagte das ich mindestens 06.35 benötige.... Bis zu welcher Version läuft das Script denn maximal, dann würde ich wieder downgraden?

**Comment by DerMitch** [comment]
Ich habs damals für 6.23 entwickelt (ja, ist schon älter) und schon eine Weile selbst nicht mehr im Einsatz. Laut der AVM-Dokumentation wurde in der 6.50+ nur die SID erzwungen, aber die schickt die Library eh schon mit.

Vor dem Wochenende werde ich wahrscheinlich nicht dazu kommen, mir das anzuschauen.

**Comment by Mc-Raw** [comment]
Wie gesagt das Abrufen der Actoren und das Auslesen des Energieverbrauch funktioniert ja auch ,dafür wird die SID normal ja auch gebraucht (ohne Passwort im Befehl klappts nämlich nicht).

**Comment by DerMitch** [comment]
Ich denke ich habe den Fehler: In der AIN ist ein Leerzeichen, das Du beim Steuern mit angeben musst. Dazu einfach die AIN in Anführungszeichen anhängen:

``` bash
python -m fritzhome --host 192.168.2.1 switch-on "00000 0000000"
```

Löst das dein Problem?

**Comment by Mc-Raw** [comment]
Ja,super, jetzt läufts! 

Mal so nebenbei.. Kann man das ganze eigentlich auch ohne die virtualenv starten,ich würde nämlich gerne per autostart über die /etc/rc.local eine Steckdose schalten..wenn ich die fritzhome datei so ausführe fehlen dateien

`fritzenv/bin$ python fritzhome`

```
Traceback (most recent call last):
  File "fritzhome", line 7, in <module>
    from fritzhome.__main__ import cli
ImportError: No module named fritzhome.__main__
```

**Comment by DerMitch** [comment]
Du kannst das virtualenv-Python direkt über seinen absoluten Pfad ansprechen, dann brauchst du das activate-Skript nicht.

``` bash
/home/mitch/venv/bin/python -m fritzhome
```

Beziehungsweise, wenn das Modul über pip installiert wurde:

``` bash
/home/mitch/venv/bin/fritzhome
```

Falls Du die Version ausm git nimmst, kannst du diese auch per pip installieren:

``` bash
. venv/bin/activate
cd fritzbox-smarthome
pip install --editable .
```
